In [166]:
import numpy as np

Basics array creation, size check , dtype and dimensions

In [167]:
a =np.array([1, 2, 3], dtype='int16')
print(a)


[1 2 3]


In [168]:
b =np.array([[1,2,3],[4,6,8]])
print(b)

[[1 2 3]
 [4 6 8]]


In [169]:
#Dimension of a
a.ndim

1

In [170]:
#dimension of b
b.ndim

2

In [171]:
#Data type of a
a.dtype

dtype('int16')

In [172]:
#Size of each element in a
a.itemsize

2

In [173]:
#Total Size of a
a.nbytes

6

In [174]:
#Data type of b and default dtype is int32
b.dtype

dtype('int32')

In [175]:
#Size of each element in b
b.itemsize

4

In [176]:
#Total size of b
b.nbytes

24

Accessing/Changing specific elements, rows, columns

In [177]:
x= np.array([[1,2,3,4,5,6,7,8],[10,11,12,13,14,15,16,17]])
print(x)

[[ 1  2  3  4  5  6  7  8]
 [10 11 12 13 14 15 16 17]]


In [178]:
# Get a specific element [row, column]
x[0,7]


8

In [179]:
x[1,3]

13

In [180]:
# Get a specific row
x[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [181]:
x[1]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [182]:
# Get a specific column
x[:,0]

array([ 1, 10])

In [183]:
x[:,7]

array([ 8, 17])

In [184]:
# Getting a little more fancy [startindex:endindex:stepsize]
#row=0, start at index 1 i.e 2,end index 6 i.e 7, stepsize 2
x[0,1:6:2]

array([2, 4, 6])

In [185]:
# updating values at specific location
x[1,5] =20
print(x)

[[ 1  2  3  4  5  6  7  8]
 [10 11 12 13 14 20 16 17]]


In [186]:
# Updating Values in entire column
x[:,2] = [1,2]
print(x)

[[ 1  2  1  4  5  6  7  8]
 [10 11  2 13 14 20 16 17]]


3d examples

In [187]:
y= np.array([[[100,200],[300,400]],[[500,600],[700,800]]])
print(y)

[[[100 200]
  [300 400]]

 [[500 600]
  [700 800]]]


In [188]:
# Get a specific element (work outside in) 
y[0,1,1]

400

In [189]:
y[:,0,:]

array([[100, 200],
       [500, 600]])

Initializing different types of arrays

In [190]:
# All zeros matrix
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [191]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [192]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

For an array created as:

```python
np.zeros((d1, d2, d3, d4))

Axis Meaning:
Axis	Meaning
d1	Number of outermost groups (e.g., batches)
d2	Number of sub-groups per outer group
d3	Number of rows
d4	Number of columns

In [193]:
#All ones matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [194]:
#Any other number matrix
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [195]:
#reusable already existing number matrix
m =np.array([[1,2],[3,4]])
np.full_like(m,7)

array([[7, 7],
       [7, 7]])

In [196]:
#Random decimal numbers matrix
np.random.rand(6,8)

array([[0.02406202, 0.82853764, 0.98769562, 0.22804942, 0.20723495,
        0.72833783, 0.56852563, 0.54356581],
       [0.6279529 , 0.11192557, 0.34345442, 0.25929299, 0.21810925,
        0.48209277, 0.99506601, 0.51142432],
       [0.69710881, 0.46062937, 0.38228613, 0.51821622, 0.50238627,
        0.58420246, 0.94729362, 0.70401953],
       [0.47375694, 0.37666485, 0.51468284, 0.9564744 , 0.69393291,
        0.74416829, 0.71968402, 0.77699889],
       [0.3566415 , 0.19780864, 0.30023483, 0.35392632, 0.31351184,
        0.03168559, 0.99697154, 0.53623713],
       [0.38591349, 0.0902217 , 0.67412166, 0.82462052, 0.05098166,
        0.75403476, 0.92554481, 0.54865852]])

In [197]:
np.random.randint(2,4,size=(3,2))

array([[3, 2],
       [2, 2],
       [2, 3]])

In [198]:
# Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [199]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [200]:
#repeating arrays
arr =np.array([[1,2]])
r1 =np.repeat(arr,3,axis=0)
print(r1)

[[1 2]
 [1 2]
 [1 2]]


In [201]:
#creating a matrix using arange and reshape
r2 =np.arange(0,20)
print(r2.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Solving a problem

In [202]:
all_1=np.ones((5,5))
print(all_1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [203]:
all_1[1:4,1:4]=0
print(all_1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [204]:
all_1[2,2]=9
print(all_1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#Mathematics operations

In [205]:
mat = np.array([1,2,100,200])
print(mat)

[  1   2 100 200]


In [206]:
mat + 2

array([  3,   4, 102, 202])

In [207]:
mat-2

array([ -1,   0,  98, 198])

In [208]:
mat * 2

array([  2,   4, 200, 400])

In [209]:
mat ** 2

array([    1,     4, 10000, 40000])

In [210]:
mat / 2

array([  0.5,   1. ,  50. , 100. ])

In [211]:
mat2 = np.array([10,20,30,40])
print(mat + mat2)

[ 11  22 130 240]


In [212]:
np.sin(mat)

array([ 0.84147098,  0.90929743, -0.50636564, -0.8732973 ])

#### DANGER ZONE ####
Alwaays use copy method while copying arrays
 !!!!  mat_copy = mat.copy()  !!!!

Linear algebra

In [213]:
a1=np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [214]:
a2=np.full((3,2), 5)
a2

array([[5, 5],
       [5, 5],
       [5, 5]])

In [215]:
# find multiplicatuion of matrix a*b with b*a   
np.matmul(a1,a2)

array([[15., 15.],
       [15., 15.]])

In [216]:
# determinant of a matrix
b1 =np.eye(6)
np.linalg.det(b1)

1.0

In [217]:
# Trace = sum of diagonal elements of a square matrix
np.trace(b1)

6.0

In [218]:

A = np.array([[1, 2],
              [3, 4]])

U, S, VT = np.linalg.svd(A)
print("U Matrix:\n", U)
print("Singular Values:\n", S)  
print("VT Matrix:\n", VT)   


U Matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values:
 [5.4649857  0.36596619]
VT Matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [219]:

# Inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [220]:
# Eigenvalues and Eigenvectors
B = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(B)
print("Eigenvalues:\n", values)
print("Eigenvectors:\n", vectors)


Eigenvalues:
 [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


In [221]:
#matrix norm = measure of matrix's magnitude
np.linalg.norm(B)

3.605551275463989

# Statistics

In [222]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [223]:
np.min(stats, axis=0)  # min of each column

array([1, 2, 3])

In [224]:
np.min(stats, axis=1)  # min of each row

array([1, 4])

In [225]:
np.max(stats)

6

In [226]:
np.max(stats, axis=0)  # max of each column

array([4, 5, 6])

In [227]:
np.max(stats, axis=1)  # max of each row

array([3, 6])

In [228]:
np.sum(stats)

21

In [229]:
np.sum(stats, axis=0)  # sum of each column

array([5, 7, 9])

In [230]:
np.sum(stats, axis=1)  # sum of each row

array([ 6, 15])

Reorganizing arrays

In [231]:
before = np.array([[1, 2, 3], [4, 5, 6]])
print("before:\n", before)

after =  before.reshape((3,2))
print("after:\n",after)

before:
 [[1 2 3]
 [4 5 6]]
after:
 [[1 2]
 [3 4]
 [5 6]]


In [232]:
#vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8]) 
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [233]:
#vertical stacking
v11 = np.ones((2,4))
v22 = np.zeros((2,4))
np.vstack([v11,v22])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [234]:
#horizontal stacking
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [235]:
#horizontal stacking
h11 = np.ones((2,4))
h22 = np.zeros((2,4))
np.hstack([h11,h22])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

Miscellaneous

In [241]:
# Load data from file 
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [243]:
#Boolean masking and advanced indexing
filedata >10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [245]:
filedata[filedata >=10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [246]:
# Index with list in a Numpy
arr = np.array([10,20,30,40,50])
arr[[1,2,4]]

array([20, 30, 50])